export const APP_NAME = 'WDP301';

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export enum ReportReason {
  INCORRECT_INFORMATION = 'INCORRECT_INFORMATION',
  SPAM = 'SPAM',
  PERMANENTLY_CLOSED = 'PERMANENTLY_CLOSED',
  WRONG_OWNER = 'WRONG_OWNER',
  OTHER = 'OTHER',
}

export enum ReportTargetType {
  LOCATION = 'LOCATION',
  REVIEW = 'REVIEW',
  USER = 'USER',
  OWNERSHIP = 'OWNERSHIP',
}

export enum ReportStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  APPEALED = 'APPEALED',
  RESOLVED = 'RESOLVED',
}

export enum ReportRoute {
  STANDARD_REVIEW = 'STANDARD_REVIEW',
  OWNERSHIP_REVIEW = 'OWNERSHIP_REVIEW',
}
